### PR TITLE
Changing solr loading commands to fail fast if solr exceptions are th…

### LINKED ISSUE #223: owltools should (usually) fail and die if any commands cannot complete (Solr loader)
In some cases, when owltools commands cannot complete as desired, they may fail but the command line will continue processing.

This can cause problems during a Solr load with some indexes getting filled and others containing little or nothing.

### PR DESCRIPTION
**Pull request by cmungall**
…rown

Previously these were caught and printed out on stderr. This is not so good as
they are buried in the masses of log messages meaning problems leak into production
potentially

Changed behavior so that exceptions are not caught. This will cause the current command
to die, and to exit with a non-zero error code. Fixes #223

Note that in two places we still wrap with a try{}, in the experimental model loading.
However, the behavior has been changed here to explicitly exit with non-zero if
any exceptions are caught

### CODE REVIEW

File: OWLTools-Runner/src/main/java/owltools/cli/SolrCommandRunner.java [hunk 1]
```diff
@@ -1255,20 +1253,9 @@ private void loadGAFDoc(String url, GafDocument gafdoc, EcoTools eco, TaxonTools
 		loader.setTaxonSubsetName(taxonSubsetName);
 		loader.setEcoSubsetName(ecoSubsetName);
 		loader.setGraph(g);
-		try {
```
Comment (kltm) [inline OWLTools-Runner/src/main/java/owltools/cli/SolrCommandRunner.java]: I'm a little sorry to see some of the debugging errors go, but let's see what it looks like in practice?

**Comment by kltm** [comment]
This would then be merged and build into a new owltools jar for AmiGO.
